/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package konversisuhu;

import java.awt.Font;
import javax.swing.table.TableModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LouisBay
 */
public class KonversiSuhuBasic extends javax.swing.JFrame {
    int baris,kol;
    private Object[][] dataTable = null;
    private String[] header = {"No","Celcius","Fahrenheit","Kelvin","Reamur","Newton","Rankine","Delisle","Romer"};
    /**
     * Creates new form Suhu
     */
    public KonversiSuhuBasic() {
        initComponents();
        tblSuhu.getTableHeader().setFont(new Font("Calibri", Font.BOLD, 18));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        proses = new javax.swing.JButton();
        nAwal = new javax.swing.JTextField();
        nAwalLabel = new javax.swing.JLabel();
        nAkhir = new javax.swing.JTextField();
        nAkhirLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSuhu = new javax.swing.JTable();
        tombolClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        proses.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        proses.setText("PROSES");
        proses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prosesActionPerformed(evt);
            }
        });

        nAwal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        nAwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nAwalActionPerformed(evt);
            }
        });

        nAwalLabel.setFont(new java.awt.Font("Tw Cen MT", 1, 28)); // NOI18N
        nAwalLabel.setText("Nilai Awal");

        nAkhir.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        nAkhir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nAkhirActionPerformed(evt);
            }
        });

        nAkhirLabel.setFont(new java.awt.Font("Tw Cen MT", 1, 28)); // NOI18N
        nAkhirLabel.setText("Nilai Akhir");

        tblSuhu.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        tblSuhu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Celcius", "Fahrenheit", "Kelvin", "Reamur", "Newton", "Rankine", "Delisle", "Romer"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSuhu.setColumnSelectionAllowed(true);
        tblSuhu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblSuhu.setFocusable(false);
        tblSuhu.setRowHeight(30);
        tblSuhu.setSurrendersFocusOnKeystroke(true);
        jScrollPane1.setViewportView(tblSuhu);
        tblSuhu.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (tblSuhu.getColumnModel().getColumnCount() > 0) {
            tblSuhu.getColumnModel().getColumn(0).setPreferredWidth(50);
            tblSuhu.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        tombolClear.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        tombolClear.setText("Clear");
        tombolClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nAwalLabel)
                    .addComponent(nAkhirLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nAwal)
                    .addComponent(nAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(144, 144, 144)
                .addComponent(proses, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(200, 200, 200))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 999, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tombolClear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nAwal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nAwalLabel))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nAkhirLabel)))
                    .addComponent(proses, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(133, 133, 133)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tombolClear, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nAwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nAwalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nAwalActionPerformed

    private void nAkhirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nAkhirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nAkhirActionPerformed

    private void prosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prosesActionPerformed
        int a = Integer.parseInt(nAwal.getText());
        int b = Integer.parseInt(nAkhir.getText());
        kol = 9;
        baris = (b-a)+1;
        dataTable = new Object[baris][kol];
        int c;
        int x = 0;
        for(c=a; c<=b ;c++){
            double fah = 1.8d * (c+32d);
            double kel = c + 273d;
            double rea = 0.8d * c;
            double ran = c*1.8d + 491.67d;
            double del = (100d-c) * 1.5d;
            double newt = c*(33d/100d);
            double rom = c*21d/40d + 7.5d;
            dataTable[x][0] = x+1;
            dataTable[x][1] = c;
            dataTable[x][2] = fah;
            dataTable[x][3] = kel;
            dataTable[x][4] = rea;
            dataTable[x][5] = newt;
            dataTable[x][6] = ran;
            dataTable[x][7] = del;
            dataTable[x][8] = rom;
            x++;
        }
        tblSuhu.setModel(new DefaultTableModel(dataTable,header));
        tblSuhu.getColumnModel().getColumn(0).setPreferredWidth(50);
        tblSuhu.getColumnModel().getColumn(0).setMaxWidth(50);

    }//GEN-LAST:event_prosesActionPerformed

    private void tombolClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolClearActionPerformed
        tblSuhu.setModel(new DefaultTableModel(null,header));
        tblSuhu.getColumnModel().getColumn(0).setPreferredWidth(50);
        tblSuhu.getColumnModel().getColumn(0).setMaxWidth(50);
        nAwal.setText("");
        nAkhir.setText("");
    }//GEN-LAST:event_tombolClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhuBasic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhuBasic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhuBasic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhuBasic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KonversiSuhuBasic().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nAkhir;
    private javax.swing.JLabel nAkhirLabel;
    private javax.swing.JTextField nAwal;
    private javax.swing.JLabel nAwalLabel;
    private javax.swing.JButton proses;
    private javax.swing.JTable tblSuhu;
    private javax.swing.JButton tombolClear;
    // End of variables declaration//GEN-END:variables
}
